#!/bin/bash

if test -z "$PORT"; then
  PORT=8080
fi

echo "Running migrations"
python manage.py migrate --noinput
python manage.py createcachetable 2>/dev/null || true

echo "Starting massbailfund"
uwsgi --ini uwsgi.ini
