[uwsgi]
chdir=/app
module=massbailfund.wsgi:application
master=true
workers=2
threads=2
pidfile=/tmp/uwsgi-master.pid
vacuum=true
thunder-lock=true
enable-threads=true
max-requests=800
http = 0.0.0.0:$(PORT)
http-keepalive = 1
http-auto-gzip = true
virtualenv = /venvs/massbailfund/
http-timeout = 30
socket-timeout = 30
harakiri = 30
log-format = %(addr) - [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) bytes %(msecs)ms
max-worker-lifetime = 1200
