# Generated by Django 6.0.3 on 2026-03-06 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('primary_type', models.CharField(choices=[('Mechanism', 'Mechanism'), ('Decision Maker', 'Decision Maker'), ('Institution', 'Institution')], max_length=50)),
                ('secondary_type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['primary_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EntityReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('Legislative/Timeline', 'Legislative/Timeline'), ('Funding Sources/Budget', 'Funding Sources/Budget'), ('Current Legislative Initiatives', 'Current Legislative Initiatives'), ('Potential Solutions', 'Potential Solutions'), ('Legal Memos / Reports', 'Legal Memos / Reports'), ('Anecdotal/Interviews', 'Anecdotal/Interviews')], max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, default='')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.entity')),
            ],
            options={
                'ordering': ['entity', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('relationship_type', models.CharField(choices=[('Administration', 'Administration'), ('Advisory', 'Advisory'), ('Decision Authority', 'Decision Authority'), ('Enforcement', 'Enforcement'), ('Monitoring', 'Monitoring'), ('Oversight', 'Oversight'), ('Role', 'Role')], max_length=50)),
                ('description', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.entity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.entity')),
            ],
            options={
                'ordering': ['source', 'target'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('membership_type', models.CharField(choices=[('Primary', 'Primary'), ('External', 'External')], max_length=20)),
                ('institution', models.ForeignKey(limit_choices_to={'primary_type': 'Institution'}, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.entity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to='core.entity')),
            ],
            options={
                'ordering': ['institution', 'membership_type', 'member'],
                'unique_together': {('institution', 'member')},
            },
        ),
    ]
