# Generated by Django 6.0.3 on 2026-03-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['primary_type', 'name'], 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterUniqueTogether(
            name='institutionmembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='institutionmembership',
            constraint=models.UniqueConstraint(fields=('institution', 'member'), name='unique_institution_member'),
        ),
    ]
