# Generated by Django 5.1.7 on 2026-03-06 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('url', models.URLField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('key_facts', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.entity')),
            ],
            options={
                'ordering': ['entity', 'title'],
            },
        ),
    ]
