# Generated by Django 6.0.3 on 2026-03-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_resource_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
