# Generated by Django 6.0.3 on 2026-03-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resource_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='resources/'),
        ),
    ]
