# Generated by Django 6.0.3 on 2026-03-06 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resource_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.entity'),
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('term', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField()),
                ('entities', models.ManyToManyField(blank=True, related_name='glossary_terms', to='core.entity')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
    ]
