# Generated by Django 6.0.3 on 2026-03-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_glossary_and_nullable_resource_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='primary_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='secondary_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='entityreference',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institutionmembership',
            name='membership_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(max_length=255),
        ),
    ]
