# Generated by Django 6.0.3 on 2026-03-07 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_choices_widen_charfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionMaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('authority_type', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subcategory', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='institutionmembership',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships_new', to='core.decisionmaker'),
        ),
        migrations.AddField(
            model_name='institutionmembership',
            name='new_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_new', to='core.institution'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='mechanisms',
            field=models.ManyToManyField(blank=True, related_name='glossary_terms', to='core.mechanism'),
        ),
        migrations.AddField(
            model_name='resource',
            name='mechanism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.mechanism'),
        ),
        migrations.CreateModel(
            name='MechanismReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, default='')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.mechanism')),
            ],
            options={
                'ordering': ['mechanism', 'category'],
            },
        ),
        migrations.CreateModel(
            name='MechanismRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('role_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('decision_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanism_roles', to='core.decisionmaker')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.mechanism')),
            ],
            options={
                'ordering': ['mechanism', 'decision_maker'],
            },
        ),
        migrations.CreateModel(
            name='DecisionMakerAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases_as_source', to='core.decisionmaker')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases_as_target', to='core.decisionmaker')),
            ],
            options={
                'verbose_name_plural': 'decision maker aliases',
                'ordering': ['source', 'target'],
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_dm_alias')],
            },
        ),
    ]
