# Generated by Django 6.0.3 on 2026-03-07 04:55

from django.db import migrations


def backfill_new_models(apps, schema_editor):
    Entity = apps.get_model("core", "Entity")
    Relationship = apps.get_model("core", "Relationship")
    EntityReference = apps.get_model("core", "EntityReference")
    InstitutionMembership = apps.get_model("core", "InstitutionMembership")
    Resource = apps.get_model("core", "Resource")
    GlossaryTerm = apps.get_model("core", "GlossaryTerm")

    Mechanism = apps.get_model("core", "Mechanism")
    DecisionMaker = apps.get_model("core", "DecisionMaker")
    Institution = apps.get_model("core", "Institution")
    MechanismReference = apps.get_model("core", "MechanismReference")
    MechanismRole = apps.get_model("core", "MechanismRole")
    DecisionMakerAlias = apps.get_model("core", "DecisionMakerAlias")

    # Maps: old Entity UUID -> new model instance
    entity_to_mechanism = {}
    entity_to_dm = {}
    entity_to_institution = {}

    # 1. Create Mechanism, DecisionMaker, Institution from Entity rows
    for entity in Entity.objects.all():
        if entity.primary_type == "Mechanism":
            mech = Mechanism.objects.create(
                id=entity.id,
                name=entity.name,
                subcategory=entity.secondary_type,
                description=entity.description,
            )
            entity_to_mechanism[entity.id] = mech
        elif entity.primary_type == "Decision Maker":
            dm = DecisionMaker.objects.create(
                id=entity.id,
                name=entity.name,
                authority_type=entity.secondary_type,
                description=entity.description,
            )
            entity_to_dm[entity.id] = dm
        elif entity.primary_type == "Institution":
            inst = Institution.objects.create(
                id=entity.id,
                name=entity.name,
                description=entity.description,
            )
            entity_to_institution[entity.id] = inst

    # 2. Create MechanismRole and DecisionMakerAlias from Relationship rows
    for rel in Relationship.objects.select_related("source", "target").all():
        src_type = rel.source.primary_type
        tgt_type = rel.target.primary_type

        if src_type == "Mechanism" and tgt_type == "Decision Maker":
            MechanismRole.objects.create(
                mechanism=entity_to_mechanism[rel.source_id],
                decision_maker=entity_to_dm[rel.target_id],
                role_type=rel.relationship_type,
                description=rel.description,
            )
        elif src_type == "Decision Maker" and tgt_type == "Decision Maker":
            DecisionMakerAlias.objects.create(
                source=entity_to_dm[rel.source_id],
                target=entity_to_dm[rel.target_id],
                description=rel.description,
            )

    # 3. Create MechanismReference from EntityReference rows
    for ref in EntityReference.objects.select_related("entity").all():
        if ref.entity_id in entity_to_mechanism:
            MechanismReference.objects.create(
                mechanism=entity_to_mechanism[ref.entity_id],
                category=ref.category,
                description=ref.description,
                link=ref.link,
            )

    # 4. Backfill InstitutionMembership new FK columns
    for im in InstitutionMembership.objects.all():
        im.new_institution = entity_to_institution.get(im.institution_id)
        im.decision_maker = entity_to_dm.get(im.member_id)
        im.save(update_fields=["new_institution", "decision_maker"])

    # 5. Backfill Resource.mechanism from Resource.entity
    for res in Resource.objects.all():
        if res.entity_id and res.entity_id in entity_to_mechanism:
            res.mechanism = entity_to_mechanism[res.entity_id]
            res.save(update_fields=["mechanism"])

    # 6. Backfill GlossaryTerm.mechanisms from GlossaryTerm.entities
    for gt in GlossaryTerm.objects.prefetch_related("entities").all():
        mech_ids = [
            entity_to_mechanism[e.id]
            for e in gt.entities.all()
            if e.id in entity_to_mechanism
        ]
        if mech_ids:
            gt.mechanisms.set(mech_ids)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_new_models_and_transitional_fks"),
    ]

    operations = [
        migrations.RunPython(backfill_new_models, migrations.RunPython.noop),
    ]
