# Generated by Django 6.0.3 on 2026-03-07 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_backfill_new_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='source',
        ),
        migrations.RemoveField(
            model_name='entityreference',
            name='entity',
        ),
        migrations.AlterField(
            model_name='institutionmembership',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.institution'),
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='target',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='entities',
        ),
        migrations.AlterModelOptions(
            name='institutionmembership',
            options={'ordering': ['institution', 'membership_type', 'decision_maker']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['mechanism', 'title']},
        ),
        migrations.RemoveConstraint(
            model_name='institutionmembership',
            name='unique_institution_member',
        ),
        migrations.AlterField(
            model_name='institutionmembership',
            name='decision_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to='core.decisionmaker'),
        ),
        migrations.AddConstraint(
            model_name='institutionmembership',
            constraint=models.UniqueConstraint(fields=('institution', 'decision_maker'), name='unique_institution_decision_maker'),
        ),
        migrations.DeleteModel(
            name='EntityReference',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.RemoveField(
            model_name='institutionmembership',
            name='member',
        ),
        migrations.RemoveField(
            model_name='institutionmembership',
            name='new_institution',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
