# Generated by Django 6.0.3 on 2026-03-07 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_old_models_and_finalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanismQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('speaker', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('source_timestamp', models.CharField(blank=True, default='', max_length=100)),
                ('link', models.URLField(blank=True, default='')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.mechanism')),
            ],
            options={
                'ordering': ['mechanism', 'speaker'],
            },
        ),
        migrations.CreateModel(
            name='MechanismTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, default='')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='core.mechanism')),
            ],
            options={
                'verbose_name_plural': 'mechanism timeline entries',
                'ordering': ['mechanism', 'date'],
            },
        ),
    ]
