# Generated by Django 6.0.3 on 2026-03-07 08:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_quote_and_timeline_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='key_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list),
        ),
    ]
