# Generated by Django 6.0.3 on 2026-03-07 08:55

from django.db import migrations


def migrate_key_facts_to_key_points(apps, schema_editor):
    Resource = apps.get_model("core", "Resource")
    for resource in Resource.objects.exclude(key_facts=""):
        facts = []
        for line in resource.key_facts.split("•"):
            cleaned = line.strip()
            if cleaned:
                facts.append(cleaned)
        if facts:
            resource.key_points = facts
            resource.save(update_fields=["key_points"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_key_points_field'),
    ]

    operations = [
        migrations.RunPython(
            migrate_key_facts_to_key_points,
            migrations.RunPython.noop,
        ),
    ]
