# Generated by Django 6.0.3 on 2026-03-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_migrate_key_facts_to_key_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='key_facts',
        ),
    ]
