# Generated by Django 6.0.3 on 2026-03-08 06:37

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_key_facts_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='key_points',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), blank=True, default=list),
        ),
    ]
