# Generated by Django 6.0.3 on 2026-08-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_create_cache_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionmembership',
            options={'ordering': ['institution', 'decision_maker']},
        ),
        migrations.RemoveField(
            model_name='institutionmembership',
            name='membership_type',
        ),
    ]
